# This is the configuration file of the plugin. Everything should be self-explanatory
# If there is anything unclear, first take a look into the GitHub wiki:
# https://github.com/CuzIm1Tigaaa/Spectator/wiki

# This is the current version of the config, DO NOT CHANGE!
# If the version changes, the plugin will automatically
# backup your current config and create the new one
ConfigVersion: 4

Settings:

  # If the plugin gets updated, players with the following permission
  # will receive a message when they join.
  # Permission: spectator.notify.update
  NotifyOnUpdate: true

  # Spectators with the first following permission will be hidden in the tablist
  # Can be bypassed by players with the second permission.
  # Permission 1: spectator.utils.hidetab
  # Permission 2: spectator.bypass.tablist
  HidePlayersInTab: true

  # Cycling players cannot be kicked by any other player.
  KickCyclingPlayer: false

  Save:

    # The players' location (where he executed /spec) will be saved
    # Otherwise when the player leaves spectator mode, he will be at
    # his current location, equals to /spectatehere.
    PlayerLocation: true

    # The players' flight mode will be saved. Otherwise, when the player
    # leaves spectator mode, he won't be he won't be flying anymore.
    # Requires allow-flight to true in server.properties!
    PlayerFlightMode: true

  Mirror:

    # Get all effects your spectator target currently has
    # Requires following permission: spectator.utils.mirroreffects
    TargetEffects: true

    # Adds all inventory content of your spectator target in your inventory
    # Requires following permission: spectator.utils.mirrorinventory
    TargetInventory: true

  Inventory:

    # Allows spectators with the following permission to see into containers their target opens
    # Only available for the following types of containers:
    # BARREL; BLAST_FURNACE; BREWING_STAND; (TRAPPED-)CHEST; DISPENSER; DROPPER; FURNACE; HOPPER; SMOKER; SHULKER_BOX; LECTERN
    # Permission: spectator.utils.opencontainers
    OpenContainers: true

    # Allows spectators with the following permission to see into their target's enderchest
    # Only when the target opens a physically enderchest!
    # Permission: spectator.utils.openenderchest
    OpenEnderChest: false

  Cycle:

    # The cycle gets paused if there are no longer any players online and will automatically restart
    # Otherwise the cycle will simply be stopped
    PauseWhenNoPlayers: false

    # Shows a bossbar to cycling players with the name of the current target
    ShowBossBar: false